import { Skill, User, WelderProfile, EmployerProfile, Inquiry } from './types';

export const mockSkills: Skill[] = [
  { id: 1, name: 'جوشکاری لوله گاز (خانگی / صنعتی)' },
  { id: 2, name: 'جوشکاری آرگون (TIG)' },
  { id: 3, name: 'جوشکاری دی‌اکسید کربن (CO2 - MIG/MAG)' },
  { id: 4, name: 'جوشکاری اسکلت و سازه‌های سنگین فلزی' },
  { id: 5, name: 'جوشکاری درب، پنجره، نرده و سایبان' },
  { id: 6, name: 'برشکاری، خم‌کاری و ورق‌کاری فلزات' },
  { id: 7, name: 'جوشکاری چدن و فلزات رنگین (مس / برنج)' },
];

export const mockUsers: User[] = [
  { id: 'usr-welder-1', phoneNumber: '09121111111', role: 'WELDER', created_at: '2026-05-10T12:00:00Z' },
  { id: 'usr-welder-2', phoneNumber: '09122222222', role: 'WELDER', created_at: '2026-06-01T15:30:00Z' },
  { id: 'usr-welder-3', phoneNumber: '09123333333', role: 'WELDER', created_at: '2026-06-15T09:45:00Z' },
  { id: 'usr-welder-4', phoneNumber: '09124444444', role: 'WELDER', created_at: '2026-07-01T11:20:00Z' },
  { id: 'usr-employer-1', phoneNumber: '09125555555', role: 'EMPLOYER', created_at: '2026-05-12T14:10:00Z' },
  { id: 'usr-employer-2', phoneNumber: '09126666666', role: 'EMPLOYER', created_at: '2026-06-10T16:00:00Z' },
  { id: 'usr-employer-3', phoneNumber: '09127777777', role: 'EMPLOYER', created_at: '2026-07-05T08:15:00Z' },
];

export const mockWelders: WelderProfile[] = [
  {
    id: 1,
    user_id: 'usr-welder-1',
    full_name: 'امیرحسین رضایی',
    home_city: 'تهران',
    active_cities: ['تهران', 'کرج', 'اسلامشهر'],
    bio: 'متخصص جوشکاری آرگون و سازه‌های صنعتی تحت فشار با ۱۵ سال سابقه کار عمرانی.',
    profile_picture_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150&q=80',
    pending_profile_picture_url: null,
    profile_picture_status: 'APPROVED',
    is_setup_completed: true,
    base_price_list: [],
    skills: [mockSkills[0], mockSkills[1], mockSkills[3]],
  },
  {
    id: 2,
    user_id: 'usr-welder-2',
    full_name: 'علیرضا حسینی',
    home_city: 'کرج',
    active_cities: ['کرج', 'شهریار'],
    bio: 'جوشکار لوله‌کشی ساختمان و درب و پنجره، دارای کارت مهارت فنی حرفه‌ای.',
    profile_picture_url: null,
    pending_profile_picture_url: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&w=150&h=150&q=80',
    profile_picture_status: 'PENDING',
    is_setup_completed: true,
    base_price_list: [],
    skills: [mockSkills[4], mockSkills[5]],
  },
  {
    id: 3,
    user_id: 'usr-welder-3',
    full_name: 'مرتضی کریمی',
    home_city: 'مشهد',
    active_cities: ['مشهد', 'طرقبه'],
    bio: 'کارگاه متحرک جوشکاری اسکلت فلزی و گاز صنعتی مجهز به ژنراتور مستقل.',
    profile_picture_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80',
    pending_profile_picture_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&h=150&q=80',
    profile_picture_status: 'PENDING',
    is_setup_completed: true,
    base_price_list: [],
    skills: [mockSkills[3], mockSkills[0]],
  },
  {
    id: 4,
    user_id: 'usr-welder-4',
    full_name: 'سجاد محمدی',
    home_city: 'تبریز',
    active_cities: ['تبریز'],
    bio: 'جوشکار آرگون و آلومینیوم با تجهیزات کامل کارگاهی.',
    profile_picture_url: null,
    pending_profile_picture_url: null,
    profile_picture_status: 'NONE',
    is_setup_completed: false,
    base_price_list: [],
    skills: [],
  },
];

export const mockEmployers: EmployerProfile[] = [
  {
    id: 1,
    user_id: 'usr-employer-1',
    company_name: 'سازه‌گستر البرز',
    contact_person: 'مهندس بابایی',
    profile_picture_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&h=150&q=80',
    pending_profile_picture_url: null,
    profile_picture_status: 'APPROVED',
    is_setup_completed: true,
  },
  {
    id: 2,
    user_id: 'usr-employer-2',
    company_name: 'فولاد راه تهران',
    contact_person: 'دکتر محمودی',
    profile_picture_url: null,
    pending_profile_picture_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&h=150&q=80',
    profile_picture_status: 'PENDING',
    is_setup_completed: true,
  },
  {
    id: 3,
    user_id: 'usr-employer-3',
    company_name: 'شخصی',
    contact_person: 'اصغر فرهادی',
    profile_picture_url: null,
    pending_profile_picture_url: null,
    profile_picture_status: 'NONE',
    is_setup_completed: true,
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: 'inq-101',
    employer_id: 'usr-employer-1',
    title: 'لوله‌کشی گاز رایزر گاز ساختمان ۵ طبقه',
    description: 'نیاز به جوشکار ماهر لوله گاز جهت اجرای لوله‌کشی گاز رایزرهای اصلی ساختمان مسکونی ۵ طبقه با تاییدیه نظام مهندسی.',
    province: 'تهران',
    city: 'تهران',
    has_blueprint: true,
    blueprint_url: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=800&q=80',
    status: 'PENDING_ESTIMATION',
    items: [],
    created_at: '2026-07-10T14:30:00Z',
    updated_at: '2026-07-10T14:30:00Z',
    employer_name: 'سازه‌گستر البرز (مهندس بابایی)',
    employer_phone: '09125555555',
  },
  {
    id: 'inq-102',
    employer_id: 'usr-employer-2',
    title: 'جوشکاری اسکلت فلزی پروژه گلستان',
    description: 'پروژه ساختمانی ۳ طبقه با ستون‌های ناودانی جفت. نقشه پیوست شده و نیاز به برشکاری دقیق طبق شاپ دراوینگ است.',
    province: 'البرز',
    city: 'کرج',
    has_blueprint: true,
    blueprint_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    status: 'PENDING_ESTIMATION',
    items: [],
    created_at: '2026-07-12T09:15:00Z',
    updated_at: '2026-07-12T09:15:00Z',
    employer_name: 'فولاد راه تهران (دکتر محمودی)',
    employer_phone: '09126666666',
  },
  {
    id: 'inq-103',
    employer_id: 'usr-employer-1',
    title: 'ساخت و نصب درب حیاط فرفورژه مجلل',
    description: 'پروژه ساخت درب حیاط دو لنگه طبق اقلام مشخص شده.',
    province: 'تهران',
    city: 'تهران',
    has_blueprint: false,
    blueprint_url: null,
    status: 'ESTIMATED',
    items: [
      { id: 'item-1', title: 'درب دو لنگه فرفورژه ۳ در ۲.۵ متر', unit: 'عدد', quantity: 1, price: 18000000 },
      { id: 'item-2', title: 'ستون نگهدارنده فلزی قوطی ۱۰*۱۰', unit: 'متر', quantity: 6, price: 1500000 },
    ],
    created_at: '2026-07-05T10:00:00Z',
    updated_at: '2026-07-06T11:20:00Z',
    employer_name: 'سازه‌گستر البرز (مهندس بابایی)',
    employer_phone: '09125555555',
  },
  {
    id: 'inq-104',
    employer_id: 'usr-employer-3',
    title: 'جوشکاری لوله گاز موتورخانه مسکونی',
    description: 'لوله‌کشی گاز مشعل دیگ‌های آب گرم موتورخانه مرکزی ساختمان اداری.',
    province: 'تهران',
    city: 'ری',
    has_blueprint: false,
    blueprint_url: null,
    status: 'BROADCASTED',
    items: [
      { id: 'item-3', title: 'لوله‌کشی فلنجی ۲ اینچ گاز مانیسمان', unit: 'متر', quantity: 24, price: 650000 },
      { id: 'item-4', title: 'نصب شیر گاز فلنجی مشعل ۲ اینچ', unit: 'عدد', quantity: 2, price: 1200000 },
    ],
    created_at: '2026-07-08T08:00:00Z',
    updated_at: '2026-07-08T12:00:00Z',
    employer_name: 'شخصی (اصغر فرهادی)',
    employer_phone: '09127777777',
  },
];
